### ISSUE TITLE
docker-compose not working. DB not initialized properly

### ISSUE THREAD

**Issue by dpopiashvili** [metasfresh/metasfresh-docker#47]
### Is this a bug or feature request?
Bug(?)

### What is the current behavior?
after running docker-compose up -d, webui won't load. Running `docker-compose logs app` shows the following errors:

pp_1       | org.adempiere.exceptions.DBException: A result was returned when none was expected.
app_1       | Additional parameters:
app_1       |  I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1000004, trxName=null]
app_1       |  IQueueProcessor: ThreadPoolQueueProcessor{name=ExecuteSQLWorkpackageProcessor, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
app_1       |  trxName: <<ThreadInherited>>
app_1       | 	SQL: /* Finally, drop the two columns we migrated */ SELECT db_alter_table('AD_AttachmentEntry', 'ALTER TABLE AD_AttachmentEntry DROP COLUMN IF EXISTS AD_Table_ID, DROP COLUMN IF EXISTS Record_ID;');
app_1       | 	at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:91)
app_1       | 	at org.compiere.util.DB.executeUpdate(DB.java:1013)
app_1       | 	at org.compiere.util.DB.executeUpdateEx(DB.java:1077)
app_1       | 	at de.metas.migration.async.ExecuteSQLWorkpackageProcessor.executeSql(ExecuteSQLWorkpackageProcessor.java:141)
app_1       | 	at de.metas.migration.async.ExecuteSQLWorkpackageProcessor.executeAfterFinishSql(ExecuteSQLWorkpackageProcessor.java:134)
app_1       | 	at de.metas.migration.async.ExecuteSQLWorkpackageProcessor.processWorkPackage(ExecuteSQLWorkpackageProcessor.java:117)
app_1       | 	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:295)
app_1       | 	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:287)
app_1       | 	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:87)
app_1       | 	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:170)
app_1       | 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
app_1       | 	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
app_1       | 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:776)
app_1       | 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:689)
app_1       | 	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:597)
app_1       | 	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:160)
app_1       | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
app_1       | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
app_1       | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
app_1       | 	at java.lang.Thread.run(Thread.java:748)
app_1       | Caused by: org.postgresql.util.PSQLException: A result was returned when none was expected.
app_1       | 	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:140)
app_1       | 	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1449)
app_1       | 	at org.adempiere.sql.impl.CPreparedStatementProxy.executeUpdate(CPreparedStatementProxy.java:138)
app_1       | 	at org.compiere.util.DB.executeUpdate(DB.java:944)
app_1       | 	... 19 common frames omitted

### Which are the steps to reproduce?
Run `docker-compose up -d`, wait few seconds and run `docker-compose logs app`

### What is the expected or desired behavior?
Well, I was hoping to see webui :-)

**Comment by metas-ts** [comment]
Hi @dpopiashvili 
thx for opening this issue, we are going to look into it.

However, I believe that it's nothing which prevents you from seeing the webui. 
This problem occurs within our app service. If it was a problem withing the webapi, the log line would start with `webapi_1` (afair, but at any rate, not with `app_1`)
It further just means that one work package could not be processed, i.e. `C_Queue_WorkPackage_ID=1000004`. 
Afair this work package is related to migrating big databases and maybe it fails on each new "vanilla" DB, but we didn't notice it yet..as I said, we shall look into it, but the webui should still start up.
Can you confirm that it eventually does?

**Comment by dpopiashvili** [comment]
Hey @metas-ts 

Thanks for the reply. Actually webui is not loading at all. That's why I thought the problem was related with database. When I try to access webui, I see just blank page and the following error in console window:

```
Uncaught (in promise) TypeError: Cannot read property 'status' of undefined
    at App.<anonymous> (scheduler.production.min.js:10)
```

I followed the instructions from README, didn't modify anything :)

**Comment by rainac** [comment]
Hi, I have a similar problem, the login is not working.

At first, the webpage is blank. This is probably due to the DB init, as mentioned in the docs. After the `docker-compose up -d` I can see one or two very busy java processes in `top`. When these settle down, the login/password form appears in the browser.

But then, I still cannot login. Both pairs of default passwords mentioned in the docs are not working. How could I check this issue, or reset the password manually?

**Comment by ramsonline** [comment]
I have the same Problem, i am not able to login at all there is only a blank screen

**Comment by senakasu** [comment]
Hi All,
I have the same problem only a blank screen. Did anyone resolve this issue? Please advise me.

**Comment by TKlerx** [comment]
Hi all,
i also have the same problem. Just started a fresh ubuntu vm and the containers are running fine with SSL certificate.
Also sucessfully followed the steps as described here:
https://forum.metasfresh.org/t/docker-install-rest-scripts-have-incorrect-cors-headers-cannot-login/1705  ( ran `docker exec -u postgres metasfresh_docker_db_1 psql -d metasfresh -c "UPDATE AD_SysConfig SET Value='http://my_metasfreshinstance.com' WHERE Name='webui.frontend.url';" `)

Any hint how to fix the issue?
Thanks!
